#! /usr/bin/python2.7
from xshop import new
from xshop import test
from xshop import build
from xshop import config
from xshop import version
import sys
args = sys.argv

#
#	new [project_type] [library] [name]
#
if args[1]=='new':
	if len(args)<5:
		print ("Insufficient arguments.")
	elif len(args)>5:
		print ("Too many arguments.")
	
	if args[2]=='test':
		new.new_test_project(args[3],args[4])
	elif args[2]=='build':
		new.new_build_project(args[3],args[4])
	else:
		print ("Project type not recognized: "+args[2])
#
#	test [source] [version]
#
elif args[1]=='test':
	if len(args)<4:
		print("Insufficient arguments.")
	elif len(args)>4:
		print("Too many arguments.")
	print test.run_test(args[3],args[2])
#
#	build			- Builds all versions which have not been successfully built 
# 	build [version] 	- Builds version specified
#	build -f		- Builds all versions
#
elif args[1]=='build':
	# Go ahead and detect versions
	c = config.Config()
	c.put('source-versions',version.detect_source(c.get('library'),'source'))
	if len(args)==2:
		build.build_multiple(False)
	elif args[2]=='-f':
		build.build_multiple(True)
	else:	
		if build.build_version(args[2]):
			bversions = c.get('built-versions')
			bversions.append(args[2])
			c.put('built-versions',bversions)
		
else:
	print ("Command not recognized: "+args[1])
		
