FROM xshop:build_image

# Some set up
ENV USER='build' LOGNAME='build'

# Add tarball
ADD {{ library }}-{{ version }}.tar.gz /home/

# Retar the file for dh-make
RUN tar -czf {{ library }}-{{ version }}.tar.gz {{ library }}-{{ version }}

# Run dh-make
WORKDIR /home/{{ library }}-{{ version }}
RUN echo 's\n\n' | dh_make -f ../{{ library }}-{{ version }}.tar.gz
RUN rm debian/*.ex debian/*.EX debian/README.*

# Copy in supplied debian configuration
ADD debian/* debian/

RUN debuild --no-lintian -S -us -uc

# Run cowbuilder on container start
CMD cowbuilder --build /home/{{ library }}_{{ version }}-1.dsc
