FROM debian:stable

RUN apt-get update
RUN apt-get -y install gcc
RUN apt-get -y install make
RUN apt-get -y install checkinstall
RUN apt-get -y install lintian
{% for dep in builddeps %}
RUN apt-get -y install {{ dep }}
{% endfor %}

# Add tarball
ADD {{ library }}-{{ version }}.tar.gz /home/

# Build
WORKDIR /home/{{ library }}-{{ version }}
RUN ./configure
RUN make
RUN checkinstall
