FROM xshop:base_test_image

#
#	Generally, the attacker runs code from the test directory, 
#
#	If you need any other software for the attack (metasploit, etc.), 
#		install it here. 
#

WORKDIR /home/
